- name: check number of namenodes
  when: groups['namenodes']|count < 1 or groups['namenodes']|count > 2
  fail: msg="expected number of namenodes is 1 or 2, you have configured {{ groups['namenodes']|count }}"
  run_once: true

- name: check number of datanodes
  when: groups['datanodes']|count < 1
  fail: msg="expected number of datanodes is more than 0, you have not configured any"
  run_once: true

- name: check number of yarnresourcemanager
  when: groups['yarnresourcemanager']|count < 1
  fail: msg="at least one node is required for yarnresoucemanager you have not configured any"
  run_once: true

- name: check number of journal nodes
  when: groups['namenodes']|count > 1 and groups['journalnodes']|count % 2 == 0
  fail: msg="expected number of journalnodes for HA setup is odd and at least 1, you have configured {{ groups['journalnodes']|count }}"
  run_once: true

- name: check number of journal nodes
  when: groups['namenodes']|count < 2 and groups['journalnodes']|count > 0
  fail: msg="{{ groups['journalnodes']|count }} journal nodes configured, however you have only 1 namenode, for HA setup at least 2 namenodes is requied"
  run_once: true

- name: check number of zookeeper nodes for namenodes
  when: groups['namenodes']|count > 1 and ( groups['zookeepernodes']|count != 3 and groups['zookeepernodes']|count != 5 )
  fail: msg="expected number of zookeeper nodes for HA setup is 3 or 5, you have configured {{ groups['zookeepernodes']|count }}"
  run_once: true

- name: check number of zookeeper nodes for resourcemanager
  when: groups['yarnresourcemanager']|count > 1 and (  groups['zookeepernodes']|count != 1 and groups['zookeepernodes']|count != 3 and groups['zookeepernodes']|count != 5 )
  fail: msg="expected number of zookeeper nodes for HA setup is 1 or 3 or 5, you have configured {{ groups['zookeepernodes']|count }}"
  run_once: true

- name: check number of hivemetastore nodes
  when: groups['hivemetastore']|count != 0 and groups['hivemetastore']|count != 1
  fail: msg="expected number of hivemetastore nodes is 0 or 1, you have configured {{ groups['hivemetastore']|count }}"
  run_once: true

- name: check hivemetastore prerequisites
  when: groups['hivemetastore']|count >  0 and groups['zookeepernodes']|count < 1
  fail: msg="hivemetastore requires at least one zookeepernode, you have not configured any"
  run_once: true

- name: check hivemetastore prerequisites
  when: groups['hivemetastore']|count > 0 and groups['postgresql']|count != 1
  fail: msg="hivemetastore requires postgresql node, you have not configured any"
  run_once: true

- name: check oozie prerequisites
  when: groups['oozie']|count > 0  and groups['postgresql']|count != 1
  fail: msg="hue requires postgresql node, you have not configured any"
  run_once: true

- name: check hue prerequisites
  when: groups['hue']|count > 0  and groups['postgresql']|count != 1
  fail: msg="hue requires postgresql node, you have not configured any"
  run_once: true

- name: check hue prerequisites
  when: groups['hue']|count > 0 and groups['oozie']|count < 1
  fail: msg="hue requires oozie node to submit jobs, you have not configured any"
  run_once: true

- name: check number of impala-state-store hosts
  when: groups['impala-store-catalog']|count > 1
  fail: msg="expected number of impala-store-catalog is 0 or 1, you have configured {{ groups['impala-store-catalog']|count }}"
  run_once: true

- name: check impala prerequisites
  when: groups['impala-store-catalog']|count > 0 and groups['hivemetastore']|count < 1
  fail: msg="impala requires hivemetastore node, you have not configured any"
  run_once: true

- name: check number of hbase master hosts
  when: groups['hbasemaster']|count > 1
  fail: msg="expected number of hbasemaster hosts is 0 or 1, you have configured {{ groups['hbasemaster']|count }}"
  run_once: true

- name: check hbase prerequisites
  when: groups['hbasemaster']|count > 0 and groups['zookeepernodes']|count < 1
  fail: msg="hbase requires at least one zookeepernode, you have not configured any"
  run_once: true

- name: check solr prerequisites
  when: groups['solr']|count > 0 and groups['zookeepernodes']|count < 1
  fail: msg="solr requires at least one zookeepernode, you have not configured any"
  run_once: true

- name: check kafka prerequisites
  when: groups['kafka']|count >  0 and groups['zookeepernodes']|count < 1
  fail: msg="kafka requires at least one zookeepernode, you have not configured any"
  run_once: true
